name: Multiple Daily Commits

on:
  schedule:
    - cron: "0 */3 * * *" # This runs every 3 hours

jobs:
  daily-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Make a Change
        run: |
          echo "Update: $(date)" >> multiple-daily-updates.txt

      - name: Commit Changes
        run: |
          git config --global user.name "barrett38"
          git config --global user.email "barrett1614@gmail.com"
          git add multiple-daily-updates.txt
          git commit -m "Update: $(date)"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # This token is provided by GitHub Actions
          # and does not need to be replaced with any other value
